import { TListItem } from './ListItem';

export const configList: TListItem[] = [
    {
        id: '1',
        title: 'Деталь (ЗАМЕНЫ / АНАЛОГИ)',
        description: '500',
        isActive: true,
    },
    {
        id: '2',
        title: 'Shaanxi/Shacman',
        description: '434',
        isActive: true,
    },
    {
        id: '3',
        title: 'Деталь (BAW/FAW/DONGFENG/JAC) jhrgherjghrejghjre',
        description: '434343',
        isActive: false,
    },
    {
        id: '4',
        title: 'Деталь (СТАЛЕР)',
        description: '767',
        isActive: false,
    },
    {
        id: '5',
        title: 'Деталь (Paraut)',
        description: '6765',
        isActive: false,
    },
    {
        id: '6',
        title: 'Деталь (ДОРОЖНЫЕ ТЕХНОЛОГИИ)',
        description: '8768',
        isActive: false,
    },
    {
        id: '7',
        title: 'Деталь (Mando)',
        description: '45',
        isActive: false,
    },
    {
        id: '8',
        title: 'Деталь (KYB)',
        description: '3465',
        isActive: true,
    },
    {
        id: '9',
        title: 'Деталь (Bosch)',
        description: '2343',
        isActive: true,
    },
    {
        id: '10',
        title: 'Деталь (NGK)',
        description: '7865',
        isActive: false,
    },
    {
        id: '11',
        title: 'Деталь (Valeo)',
        description: '999',
        isActive: true,
    },
    {
        id: '12',
        title: 'Деталь (SKF)',
        description: '3478',
        isActive: false,
    },
    {
        id: '13',
        title: 'Деталь (Gates)',
        description: '647',
        isActive: true,
    },
    {
        id: '14',
        title: 'Деталь (Denso)',
        description: '890',
        isActive: false,
    },
    {
        id: '15',
        title: 'Деталь (Mann-Filter)',
        description: '1293',
        isActive: true,
    },
    {
        id: '16',
        title: 'Деталь (Sachs)',
        description: '7694',
        isActive: false,
    },
    {
        id: '17',
        title: 'Деталь (Ferodo)',
        description: '4859',
        isActive: true,
    },
    {
        id: '18',
        title: 'Деталь (Hella)',
        description: '689',
        isActive: false,
    },
    {
        id: '19',
        title: 'Деталь (Osram)',
        description: '493',
        isActive: true,
    },
    {
        id: '20',
        title: 'Деталь (TRW)',
        description: '678',
        isActive: false,
    },
    {
        id: '21',
        title: 'Деталь (Philips)',
        description: '6758',
        isActive: true,
    },
    {
        id: '22',
        title: 'Деталь (Lucas)',
        description: '987',
        isActive: false,
    },
    {
        id: '23',
        title: 'Деталь (VDO)',
        description: '3445',
        isActive: true,
    },
    {
        id: '24',
        title: 'Деталь (Mahle)',
        description: '7788',
        isActive: false,
    },
    {
        id: '25',
        title: 'Деталь (Champion)',
        description: '1234',
        isActive: true,
    },
    {
        id: '26',
        title: 'Деталь (Beru)',
        description: '6654',
        isActive: false,
    },
    {
        id: '27',
        title: 'Деталь (Lemforder)',
        description: '4543',
        isActive: true,
    },
    {
        id: '28',
        title: 'Деталь (Febi)',
        description: '5678',
        isActive: false,
    },
    {
        id: '29',
        title: 'Деталь (Textar)',
        description: '9876',
        isActive: true,
    },
    {
        id: '30',
        title: 'Деталь (Brembo)',
        description: '2312',
        isActive: false,
    },
    {
        id: '31',
        title: 'Деталь (Monroe)',
        description: '4789',
        isActive: true,
    },
    {
        id: '32',
        title: 'Деталь (ATE)',
        description: '1239',
        isActive: false,
    },
    {
        id: '33',
        title: 'Деталь (Continental)',
        description: '9945',
        isActive: true,
    },
    {
        id: '34',
        title: 'Деталь (Knecht)',
        description: '4756',
        isActive: false,
    },
    {
        id: '35',
        title: 'Деталь (WIX)',
        description: '8493',
        isActive: true,
    },
    {
        id: '36',
        title: 'Деталь (Mobil)',
        description: '985',
        isActive: false,
    },
    {
        id: '37',
        title: 'Деталь (Total)',
        description: '2134',
        isActive: true,
    },
    {
        id: '38',
        title: 'Деталь (Castrol)',
        description: '7785',
        isActive: false,
    },
    {
        id: '39',
        title: 'Деталь (Elf)',
        description: '3412',
        isActive: true,
    },
    {
        id: '40',
        title: 'Деталь (Motul)',
        description: '5544',
        isActive: false,
    },
    {
        id: '41',
        title: 'Деталь (Liqui Moly)',
        description: '6345',
        isActive: true,
    },
    {
        id: '42',
        title: 'Деталь (FAG)',
        description: '9983',
        isActive: false,
    },
    {
        id: '43',
        title: 'Деталь (INA)',
        description: '3345',
        isActive: true,
    },
    {
        id: '44',
        title: 'Деталь (Corteco)',
        description: '5532',
        isActive: false,
    },
    {
        id: '45',
        title: 'Деталь (MEYLE)',
        description: '4312',
        isActive: true,
    },
    {
        id: '46',
        title: 'Деталь (SWAG)',
        description: '3421',
        isActive: false,
    },
    {
        id: '47',
        title: 'Деталь (Delphi)',
        description: '9876',
        isActive: true,
    },
    {
        id: '48',
        title: 'Деталь (BILSTEIN)',
        description: '6543',
        isActive: false,
    },
    {
        id: '49',
        title: 'Деталь (UFI)',
        description: '7789',
        isActive: true,
    },
    {
        id: '50',
        title: 'Деталь (K&N)',
        description: '6785',
        isActive: false,
    },
];
