import { TListItemConfig } from '../list-controller/ListItem';

export const initConfigList: TListItemConfig[] = [
    {
        id: '1',
        title: 'Деталь (ЗАМЕНЫ / АНАЛОГИ)',
        subTitle: '500',
        isActive: true,
    },
    {
        id: '2',
        title: 'Shaanxi/Shacman',
        subTitle: '434',
        isActive: true,
    },
    {
        id: '3',
        title: 'Деталь (BAW/FAW/DONGFENG/JAC) jhrgherjghrejghjre',
        subTitle: '43434',
        isActive: false,
    },
    {
        id: '4',
        title: 'Деталь (СТАЛЕР)',
        subTitle: '767',
        isActive: false,
    },
    {
        id: '5',
        title: 'Деталь (Paraut)',
        subTitle: '6765',
        isActive: false,
    },
    {
        id: '6',
        title: 'Деталь (ДОРОЖНЫЕ ТЕХНОЛОГИИ)',
        subTitle: '8768',
        isActive: false,
    },
    {
        id: '7',
        title: 'Деталь (Mando)',
        subTitle: '45',
        isActive: false,
    },
    {
        id: '8',
        title: 'Деталь (KYB)',
        subTitle: '3465',
        isActive: true,
    },
    {
        id: '9',
        title: 'Деталь (Bosch)',
        subTitle: '2343',
        isActive: true,
    },
    {
        id: '10',
        title: 'Деталь (NGK)',
        subTitle: '7865',
        isActive: false,
    },
    {
        id: '11',
        title: 'Деталь (Valeo)',
        subTitle: '999',
        isActive: true,
    },
    {
        id: '12',
        title: 'Деталь (SKF)',
        subTitle: '3478',
        isActive: false,
    },
    {
        id: '13',
        title: 'Деталь (Gates)',
        subTitle: '647',
        isActive: true,
    },
    {
        id: '14',
        title: 'Деталь (Denso)',
        subTitle: '890',
        isActive: false,
    },
    {
        id: '15',
        title: 'Деталь (Mann-Filter)',
        subTitle: '1293',
        isActive: true,
    },
    {
        id: '16',
        title: 'Деталь (Sachs)',
        subTitle: '7694',
        isActive: false,
    },
    {
        id: '17',
        title: 'Деталь (Ferodo)',
        subTitle: '4859',
        isActive: true,
    },
    {
        id: '18',
        title: 'Деталь (Hella)',
        subTitle: '689',
        isActive: false,
    },
    {
        id: '19',
        title: 'Деталь (Osram)',
        subTitle: '493',
        isActive: true,
    },
    {
        id: '20',
        title: 'Деталь (TRW)',
        subTitle: '678',
        isActive: false,
    },
    {
        id: '21',
        title: 'Деталь (Philips)',
        subTitle: '6758',
        isActive: true,
    },
    {
        id: '22',
        title: 'Деталь (Lucas)',
        subTitle: '987',
        isActive: false,
    },
    {
        id: '23',
        title: 'Деталь (VDO)',
        subTitle: '3445',
        isActive: true,
    },
    {
        id: '24',
        title: 'Деталь (Mahle)',
        subTitle: '7788',
        isActive: false,
    },
    {
        id: '25',
        title: 'Деталь (Champion)',
        subTitle: '1234',
        isActive: true,
    },
    {
        id: '26',
        title: 'Деталь (Beru)',
        subTitle: '6654',
        isActive: false,
    },
    {
        id: '27',
        title: 'Деталь (Lemforder)',
        subTitle: '4543',
        isActive: true,
    },
    {
        id: '28',
        title: 'Деталь (Febi)',
        subTitle: '5678',
        isActive: false,
    },
    {
        id: '29',
        title: 'Деталь (Textar)',
        subTitle: '9876',
        isActive: true,
    },
    {
        id: '30',
        title: 'Деталь (Brembo)',
        subTitle: '2312',
        isActive: false,
    },
    {
        id: '31',
        title: 'Деталь (Monroe)',
        subTitle: '4789',
        isActive: true,
    },
    {
        id: '32',
        title: 'Деталь (ATE)',
        subTitle: '1239',
        isActive: false,
    },
    {
        id: '33',
        title: 'Деталь (Continental)',
        subTitle: '9945',
        isActive: true,
    },
    {
        id: '34',
        title: 'Деталь (Knecht)',
        subTitle: '4756',
        isActive: false,
    },
    {
        id: '35',
        title: 'Деталь (WIX)',
        subTitle: '8493',
        isActive: true,
    },
    {
        id: '36',
        title: 'Деталь (Mobil)',
        subTitle: '985',
        isActive: false,
    },
    {
        id: '37',
        title: 'Деталь (Total)',
        subTitle: '2134',
        isActive: true,
    },
    {
        id: '38',
        title: 'Деталь (Castrol)',
        subTitle: '7785',
        isActive: false,
    },
    {
        id: '39',
        title: 'Деталь (Elf)',
        subTitle: '3412',
        isActive: true,
    },
    {
        id: '40',
        title: 'Деталь (Motul)',
        subTitle: '5544',
        isActive: false,
    },
    {
        id: '41',
        title: 'Деталь (Liqui Moly)',
        subTitle: '6345',
        isActive: true,
    },
    {
        id: '42',
        title: 'Деталь (FAG)',
        subTitle: '9983',
        isActive: false,
    },
    {
        id: '43',
        title: 'Деталь (INA)',
        subTitle: '3345',
        isActive: true,
    },
    {
        id: '44',
        title: 'Деталь (Corteco)',
        subTitle: '5532',
        isActive: false,
    },
    {
        id: '45',
        title: 'Деталь (MEYLE)',
        subTitle: '4312',
        isActive: true,
    },
    {
        id: '46',
        title: 'Деталь (SWAG)',
        subTitle: '3421',
        isActive: false,
    },
    {
        id: '47',
        title: 'Деталь (Delphi)',
        subTitle: '9876',
        isActive: true,
    },
    {
        id: '48',
        title: 'Деталь (BILSTEIN)',
        subTitle: '6543',
        isActive: false,
    },
    {
        id: '49',
        title: 'Деталь (UFI)',
        subTitle: '7789',
        isActive: true,
    },
    {
        id: '50',
        title: 'Деталь (K&N)',
        subTitle: '6785',
        isActive: false,
    },
];
