import { TListItemConfig } from '../list-controller/ListItem';

export const initConfigVendorList: TListItemConfig[] = [
    { id: '1', title: 'Волжский Автотрейд', subTitle: '500', isActive: true },
    { id: '2', title: 'Siberian Auto Supply', subTitle: '434', isActive: false },
    { id: '3', title: 'МосАвтоКомпонент', subTitle: '786', isActive: true },
    { id: '4', title: 'Nippon Parts Distribution', subTitle: '348', isActive: false },
    { id: '5', title: 'VolgaTech Logistics', subTitle: '645', isActive: true },
    { id: '6', title: 'RedBear Trade', subTitle: '213', isActive: false },
    { id: '7', title: 'TitanAuto Export', subTitle: '534', isActive: true },
    { id: '8', title: 'LadaMaster Supply', subTitle: '843', isActive: false },
    { id: '9', title: 'Vortex Distribution', subTitle: '642', isActive: true },
    { id: '10', title: 'KAMAZ Logistics', subTitle: '759', isActive: true },
    { id: '11', title: 'Arctic Auto Parts', subTitle: '365', isActive: false },
    { id: '12', title: 'Skyline Autoparts', subTitle: '842', isActive: true },
    { id: '13', title: 'AlphaTech Distribution', subTitle: '478', isActive: false },
    { id: '14', title: 'GigaSupply', subTitle: '999', isActive: true },
    { id: '15', title: 'Stealth Components', subTitle: '387', isActive: false },
    { id: '16', title: 'Московский АвтоПром', subTitle: '623', isActive: true },
    { id: '17', title: 'ZETA Auto Logistics', subTitle: '452', isActive: false },
    { id: '18', title: 'Borealis Supply Chain', subTitle: '531', isActive: true },
    { id: '19', title: 'Tundra Trade', subTitle: '754', isActive: false },
    { id: '20', title: 'NovaSpeed Imports', subTitle: '623', isActive: true },
    { id: '21', title: 'IronClad Transport', subTitle: '458', isActive: false },
    { id: '22', title: 'Drakon Oil Distribution', subTitle: '723', isActive: true },
    { id: '23', title: 'ProTech Logistics', subTitle: '564', isActive: false },
    { id: '24', title: 'Thunder Brakes Supply', subTitle: '987', isActive: true },
    { id: '25', title: 'MEGA Auto Warehouse', subTitle: '359', isActive: false },
    { id: '26', title: 'Solaris Distribution', subTitle: '852', isActive: true },
    { id: '27', title: 'GlacierCool Import', subTitle: '743', isActive: false },
    { id: '28', title: 'WindStorm Parts Trading', subTitle: '462', isActive: true },
    { id: '29', title: 'EchoDrive Exports', subTitle: '359', isActive: false },
    { id: '30', title: 'LuxeSpeed Supplies', subTitle: '751', isActive: true },
];
