import { TListItemConfig } from '../list-controller/ListItem';

export const initConfigBrandList: TListItemConfig[] = [
    { id: '1', title: 'Деталь (Техномаш)', subTitle: '500', isActive: true },
    { id: '2', title: 'Деталь (Siberian Auto Parts)', subTitle: '434', isActive: false },
    { id: '3', title: 'Деталь (УралПромКомплект)', subTitle: '786', isActive: true },
    { id: '4', title: 'Деталь (NipponTech)', subTitle: '348', isActive: false },
    { id: '5', title: 'Деталь (VolgaDrive)', subTitle: '645', isActive: true },
    { id: '6', title: 'Деталь (RedBear Parts)', subTitle: '213', isActive: false },
    { id: '7', title: 'Деталь (TitanBrake)', subTitle: '534', isActive: true },
    { id: '8', title: 'Деталь (LadaPro)', subTitle: '843', isActive: false },
    { id: '9', title: 'Деталь (Vortex Precision)', subTitle: '642', isActive: true },
    { id: '10', title: 'Деталь (KAMAZ Master)', subTitle: '759', isActive: true },
    { id: '11', title: 'Деталь (Arctic Engine)', subTitle: '365', isActive: false },
    { id: '12', title: 'Деталь (Skyline Motors)', subTitle: '842', isActive: true },
    { id: '13', title: 'Деталь (AlphaTech)', subTitle: '478', isActive: false },
    { id: '14', title: 'Деталь (GigaDrive)', subTitle: '999', isActive: true },
    { id: '15', title: 'Деталь (Stealth Auto)', subTitle: '387', isActive: false },
    { id: '16', title: 'Деталь (Московский Автозавод)', subTitle: '623', isActive: true },
    { id: '17', title: 'Деталь (ZETA Parts)', subTitle: '452', isActive: false },
    { id: '18', title: 'Деталь (Borealis Filters)', subTitle: '531', isActive: true },
    { id: '19', title: 'Деталь (Tundra Drive)', subTitle: '754', isActive: false },
    { id: '20', title: 'Деталь (NovaSpeed)', subTitle: '623', isActive: true },
    { id: '21', title: 'Деталь (IronClad Bearings)', subTitle: '458', isActive: false },
    { id: '22', title: 'Деталь (Drakon Oil)', subTitle: '723', isActive: true },
    { id: '23', title: 'Деталь (ProTech Auto)', subTitle: '564', isActive: false },
    { id: '24', title: 'Деталь (Thunder Brakes)', subTitle: '987', isActive: true },
    { id: '25', title: 'Деталь (MEGA Filters)', subTitle: '359', isActive: false },
    { id: '26', title: 'Деталь (Solaris Auto)', subTitle: '852', isActive: true },
];
