import { TListItemConfig } from '../list-controller/ListItem';

export const initConfigStoreList: TListItemConfig[] = [
    { id: '1', title: 'Центральный Автосклад', subTitle: '500', isActive: true },
    { id: '2', title: 'Siberian Parts Hub', subTitle: '434', isActive: false },
    { id: '3', title: 'Логистический Центр Юг', subTitle: '786', isActive: true },
    { id: '4', title: 'Nippon Storage Facility', subTitle: '348', isActive: false },
    { id: '5', title: 'Северо-Западный Склад', subTitle: '645', isActive: true },
    { id: '6', title: 'RedBear Warehouse', subTitle: '213', isActive: false },
    { id: '7', title: 'Titan Auto Storage', subTitle: '534', isActive: true },
    { id: '8', title: 'Лада Логистик', subTitle: '843', isActive: false },
    { id: '9', title: 'Vortex Distribution Hub', subTitle: '642', isActive: true },
    { id: '10', title: 'KAMAZ Mega Storage', subTitle: '759', isActive: true },
    { id: '11', title: 'Арктический Склад Авто', subTitle: '365', isActive: false },
    { id: '12', title: 'Skyline Parts Depot', subTitle: '842', isActive: true },
    { id: '13', title: 'AlphaTech AutoStock', subTitle: '478', isActive: false },
    { id: '14', title: 'GigaSupply Center', subTitle: '999', isActive: true },
    { id: '15', title: 'Stealth Reserve', subTitle: '387', isActive: false },
    { id: '16', title: 'Московский Центр Запасов', subTitle: '623', isActive: true },
    { id: '17', title: 'ZETA Auto Storage', subTitle: '452', isActive: false },
    { id: '18', title: 'Borealis Parts Depot', subTitle: '531', isActive: true },
    { id: '19', title: 'Tundra Logistics', subTitle: '754', isActive: false },
    { id: '20', title: 'NovaSpeed Inventory', subTitle: '623', isActive: true },
    { id: '21', title: 'IronClad Stockhouse', subTitle: '458', isActive: false },
    { id: '22', title: 'Drakon Oil Depot', subTitle: '723', isActive: true },
    { id: '23', title: 'ProTech Logistics Base', subTitle: '564', isActive: false },
    { id: '24', title: 'Thunder Brakes Storage', subTitle: '987', isActive: true },
    { id: '25', title: 'MEGA Auto Vault', subTitle: '359', isActive: false },
    { id: '26', title: 'Solaris Distribution Hub', subTitle: '852', isActive: true },
    { id: '27', title: 'GlacierCool Reserve', subTitle: '743', isActive: false },
    { id: '28', title: 'WindStorm Warehouse', subTitle: '462', isActive: true },
    { id: '29', title: 'EchoDrive Storage', subTitle: '359', isActive: false },
    { id: '30', title: 'LuxeSpeed Auto Stock', subTitle: '751', isActive: true },
];
